<?php

function threeminutes_help($path, $arg) {
switch($path) {

case "admin/help#threeminutes":
return '<p>' . t("A three minute module") . '</p>';
break;
}

}

function threeminutes_menu() {
$items['threeminutes-page'] = array(
'page callback' => 'threeminutes_page',
'access arguments' => array('access content'),
'type' => MENU_CALLBACK,
);
return $items;
}

function threeminutes_page() {

return "Hello World how you doing";
}

